### PR TITLE
wording

### PR DESCRIPTION
**Pull request by MagikCow**
more user friendly; bugging sounds like you don't want them.

### CODE REVIEW

**Comment by bgerstle** [comment]
@MagikCow wasn't intended that way, I guess my "buggy" wordplay wasn't punny enough :cry:. @coreyfloyd, thoughts?

**Comment by coreyfloyd** [comment]
:+1:

**Comment by montehurd** [comment]
Ya sure!

**Comment by bgerstle** [comment]
Thanks @MagikCow! just merged this via Gerrit: https://gerrit.wikimedia.org/r/#/c/223219/ will show up here shortly

**Comment by MagikCow** [comment]
Thanks!

**Pull request closed without merging**
